# -*- coding: utf-8 -*-

"""
    apimaticcalculator

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from apimaticcalculator.decorators import lazy_property
from apimaticcalculator.configuration import Configuration
from apimaticcalculator.controllers.simple_calculator_controller import SimpleCalculatorController


class ApimaticcalculatorClient(object):

    config = Configuration

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()


